name: Destroy Infrastructure

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      confirm:
        description: "Type 'destroy' to confirm"
        required: true
        default: "cancel"

jobs:
  destroy:
    if: github.event.inputs.confirm == 'destroy'  # Double confirmation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="bucket_name=${{ vars.BUCKET_NAME }}"
        #run: terraform destroy -auto-approve -var="bucket_name=${{ secrets.BUCKET_NAME }}"